services:
  - type: web
    name: biteheist-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
